name: Deploy to Aliyun

on:
  release:
    types: [published] 

  workflow_dispatch:  
  # push:
  #   branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USER }}
          key: ${{ secrets.ALIYUN_SSH_KEY }}
          script: |
            cd /home/xmem/Xmem
            git pull origin main
            docker compose build
            docker compose up -d
